from django.conf import settings

# Ref: http://support.addthis.com/customer/portal/articles/1337994-the-addthis_config-variable
ADDTHIS_SETTINGS = getattr(settings, 'ADDTHIS_SETTINGS', {})

if not 'USERNAME' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'USERNAME': ''})

if not 'SERVICES_EXCLUDE' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'SERVICES_EXCLUDE': ''})
if not 'SERVICES_COMPACT' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'SERVICES_COMPACT': ''})
if not 'SERVICES_EXPANDED' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'SERVICES_EXPANDED': ''})
if not 'SERVICES_CUSTOM' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'SERVICES_CUSTOM': ''})

if not 'UI_CLICK' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_CLICK': False})
if not 'UI_DELAY' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_DELAY': 0})
if not 'UI_HOVER_DIRECTION' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_HOVER_DIRECTION': 0})
if not 'UI_LANGUAGE' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_LANGUAGE': ''})
if not 'UI_OFFSET_TOP' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_OFFSET_TOP': 0})
if not 'UI_OFFSET_LEFT' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_OFFSET_LEFT': 0})
if not 'UI_HEADER_COLOR' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_HEADER_COLOR': ''})
if not 'UI_HEADER_BACKGROUND' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_HEADER_BACKGROUND': ''})
if not 'UI_COBRAND' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_COBRAND': ''})
if not 'UI_USE_CSS' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_USE_CSS': True})
if not 'UI_USE_ADDRESSBOOK' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_USE_ADDRESSBOOK': False})
if not 'UI_508_COMPLIANT' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'UI_508_COMPLIANT': False})

if not 'DATA_TRACK_CLICKBACK' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'DATA_TRACK_CLICKBACK': True})
if not 'DATA_GA_TRACKER' in ADDTHIS_SETTINGS:
    ADDTHIS_SETTINGS.update({'DATA_GA_TRACKER': ''})
